class Autogenerated {
  Data? data;

  Autogenerated({this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    data = json['data'] != null ? Data.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class Data {
  List<Ability>? allAbilities;

  Data({this.allAbilities});

  Data.fromJson(Map<String, dynamic> json) {
    if (json['allAbilities'] != null) {
      allAbilities = <Ability>[];
      json['allAbilities'].forEach((v) {
        allAbilities!.add(Ability.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    if (allAbilities != null) {
      data['allAbilities'] = allAbilities!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Ability {
  String? name;
  int? id;
  String? effect;

  Ability({this.name, this.id, this.effect});

  Ability.fromJson(Map<String, dynamic> json) {
    name = json['name'];
    id = json['id'];
    effect = json['effect'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['name'] = name;
    data['id'] = id;
    data['effect'] = effect;
    return data;
  }
}
